# Generated by Django 4.2.2 on 2023-07-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekday',
            new_name='Weekday4',
        ),
    ]
