# Generated by Django 4.2.2 on 2023-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_weekday_weekday4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=50)),
                ('w_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Weekday4',
        ),
    ]
